environment = "__ENV__"
cluster-name = "__CLUSTER_NAME__"
customer = "__CUSTOMER_NAME__"
vpc_id = "__VPC_ID__"
master_subnet_ids = ["__MASTER_SUBNET_1__", "__MASTER_SUBNET_2__"]
node_subnet_ids = ["__NODE_SUBNET_1__", "__NODE_SUBNET_2__"]
ssh_key_name = "__SSH_KEY__"
vpn_ssl_pool = "__VPN_POOL__"
instance_type = "__INSTANE_TYPE__"
root_volume_size = "__VOLUME_SIZE__"
min_nodes = "__MIN__"
max_nodes = "__MAX__"
